### ISSUE TITLE
Google Drive API Permission meta data (expirationTime) not returned

### ISSUE THREAD

**Issue by gouravsood** [google/google-api-java-client#1031] opened 2017-01-07 02:52 UTC
Hi,

Google Drive API Permission meta data (id,kind,role,type,expirationTime) is not returning the expirationTime. It just returns the id,kind,role,type. 

Below is the code which was used to fetch the data:

`drive.permissions().get(fileId,permissionId).setFields("id,kind,role,type,expirationTime").execute()`

Below is the response received from google api
 ```
{
"kind": "drive#permission",
"id": "anyoneWithLink",
 "type": "anyone",
 "role": "reader"
}
```
Can you please help me in fetching the expirationTime?

Thanks,
Gourav.

**Comment by mattwhisenhunt** [comment] 2017-12-22 22:38
Have you been able to reproduce this with [API Explorer](https://developers.google.com/apis-explorer/#search/drive%20permission/m/drive/v3/drive.permissions.get)?

**Comment by mattwhisenhunt** [comment] 2018-01-07 22:34
Thank you for filing this issue. We asked some clarifying questions a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to comment with more information and we will re-open this issue.

**Closed by mattwhisenhunt** 2018-01-07 22:34 UTC
Labels: status: investigating

**Comment by gouravsood** [comment] 2018-01-07 23:13
@mattwhisenhunt sorry for the responding late on this issue. Yes, I replicated on the same on API Explorer and it was same behaviour there as well.

**Comment by mattwhisenhunt** [comment] 2018-01-08 00:36
Okay, it looks like it is a valid bug in the API (not this client library). I noticed files.get offer permissions as a valid fields entry but returns an incomplete list there too.

Bugs for the actual APIs are managed in [Issue Tracker](https://issuetracker.google.com/issues?q=componentid:191650%2B%20status:open). It looks like there is at least one related bug https://issuetracker.google.com/issues/67991925, you may want to just add a comment with more detail instead of waiting for a new one to be reviewed and assigned.

**Comment by gouravsood** [comment] 2018-01-08 10:38
Thanks @mattwhisenhunt. I have commented on https://issuetracker.google.com/issues/36760655 issue which appeared to be relevant to this issue.
