### ISSUE TITLE
Pagnitor Interface

### ISSUE THREAD

**Issue by wonderfly** [google/google-api-java-client#410] opened 2015-01-10 02:35 UTC
_From [alon.alb...@gmail.com](https://code.google.com/u/103288386859253988353/) on January 20, 2012 09:40:47_

Make classes that support paginated items implement an interface that exposes this functionality:

Something like:

class Calendar.Events.List extends JsonHttpRequest implements PagniatorRequest

interface PagniatorRequest {
  void setPageToken(String pageToken);
}

This is so a general purpose helper class can be written to implement paging code that can be shared between different model classes - Calendar & Contacts for example.

There is a workarround by calling JsonHttpRequesr.set("pageToke", value) but exposing in an interface makes this more discoverable, easier to use.

_Original issue: http://code.google.com/p/google-api-java-client/issues/detail?id=395_

**Comment by mattwhisenhunt** [comment] 2018-01-10 01:29
Duplicate of #408

**Closed by mattwhisenhunt** 2018-01-10 01:29 UTC
Labels: 2–5 stars, Component-Google-APIs, imported, priority: p1, type: feature request
