### ISSUE TITLE
Add manifest entries in jar to make it a valid OSGi bundle

### ISSUE THREAD

**Issue by amergey** [google/google-api-java-client#945] opened 2015-06-02 11:48 UTC
Add manifest entries in jar to make it a valid OSGi bundle to make it usable in osgi environment
like other google lib (guava for example)

I will submit a pull request

**Comment by mattwhisenhunt** [comment] 2017-12-22 21:30
Duplicate of #1018

**Closed by mattwhisenhunt** 2017-12-22 21:30 UTC
