### ISSUE TITLE
NullPointerException processing GoogleRefreshTokenRequest

### ISSUE THREAD

**Issue by artgo** [google/google-api-java-client#932] opened 2015-03-10 19:40 UTC
java.lang.NullPointerException: null
    at com.google.api.client.repackaged.com.google.common.base.Preconditions.checkNotNull(Preconditions.java:191) ~[google-http-client-1.19.0.jar:1.19.0]
    at com.google.api.client.util.Preconditions.checkNotNull(Preconditions.java:127) ~[google-http-client-1.19.0.jar:1.19.0]
    at com.google.api.client.json.jackson2.JacksonFactory.createJsonParser(JacksonFactory.java:92) ~[google-http-client-jackson2-1.19.0.jar:1.19.0]
    at com.google.api.client.json.JsonObjectParser.parseAndClose(JsonObjectParser.java:85) ~[google-http-client-1.19.0.jar:1.19.0]
    at com.google.api.client.json.JsonObjectParser.parseAndClose(JsonObjectParser.java:81) ~[google-http-client-1.19.0.jar:1.19.0]
    at com.google.api.client.auth.oauth2.TokenResponseException.from(TokenResponseException.java:88) ~[google-oauth-client-1.19.0.jar:1.19.0]
    at com.google.api.client.auth.oauth2.TokenRequest.executeUnparsed(TokenRequest.java:287) ~[google-oauth-client-1.19.0.jar:1.19.0]
    at com.google.api.client.googleapis.auth.oauth2.GoogleRefreshTokenRequest.execute(GoogleRefreshTokenRequest.java:125) ~[google-api-client-1.19.1.jar:1.19.1]

**Comment by artgo** [comment] 2015-03-12 04:45
I added logging to com.google.api on DEBUG level and see "HTTP/1.1 401 Unauthorized" response with empty body returned.

This definitely needs to be fixed to produce more sensible exception, since NPE usually indicate an issue with the library in this case.

**Comment by wonderfly** [comment] 2015-03-12 04:51
This is a duplicated issue and a fix is checked in:
https://github.com/google/google-oauth-java-client/commit/950fd017b57bda99c89d45771025a576e95cb7e2

The next release, which is under way, will have the fix. For the interim, you could build the libraries from HEAD.

**Comment by artgo** [comment] 2015-03-12 05:08
Thank you, @wonderfly ! Is there any timeline to release the new version?

**Comment by wonderfly** [comment] 2015-03-12 05:09
It's scheduled next week.

On Wed, Mar 11, 2015 at 10:08 PM, Artem Golubev <notifications@github.com>
wrote:

> Thank you, @wonderfly <https://github.com/wonderfly> ! Is there any
> timeline to release the new version?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/google-api-java-client/issues/932#issuecomment-78424705>
> .
>



-- 
Best,
Daniel

**Comment by artgo** [comment] 2015-03-12 05:10
:fireworks: :dancers:

**Comment by aerodc** [comment] 2015-03-23 16:59
Hello, I use version 1.20 now, but always have such erreur when refreshToken :

com.google.api.client.auth.oauth2.TokenResponseException: 401 Unauthorized

**Comment by wonderfly** [comment] 2015-03-23 21:20
That could be caused by many things: invalid client ID, client secret or
scopes. But it could also be due to refresh token overuse:

https://developers.google.com/accounts/docs/OAuth2#basicsteps
(Take a look at the special note trailing the 4th bullet)

How often do you send refreshToken requests and how often do you get 401s?



On Mon, Mar 23, 2015 at 9:59 AM, dc <notifications@github.com> wrote:

> Hello, I use version 1.20 now, but always have such erreur when
> refreshToken :
>
> com.google.api.client.auth.oauth2.TokenResponseException: 401 Unauthorized
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/google-api-java-client/issues/932#issuecomment-85096066>
> .
>



-- 
Best,
Daniel

**Comment by Zeimyth** [comment] 2015-07-10 17:00
@wonderfly I am seeing the same error as @aerodc. I am using v2-rev165-1.20.0.

I know for sure that this is not a client ID problem, nor a client secret problem, because I can perfectly reproduce cases where I get the 401 and cases where I don't. Cases where I get the 401 go something like this:

1. A user who has never used my app with their Google account logs in using Google Single Sign-on. My app requests the email and profile scopes.
2. This user later decides they want to use my app's Drive integration. They link their account on my app to Google Drive. My app requests the email, profile, drive.file, install, and offline scopes.
3. Requests to Google Drive using this user's access token work. Refreshing this user's access token works (as verified by waiting a day and repeating the aformentioned request successfully). Requests to Google Drive using my app's service account on this user's behalf always return a 401.

However, if I do things slightly differently, I can avoid the 401 altogether:

1. A user who has never used my app signs up without using Google SSO.
   * Alternatively, the user from the previous steps unlinks their Drive account with my app and revokes all permissions they had given to my app
2. The user decides they want to use my app's Drive integration. They link their account, and my app requests the email, profile, drive.file, install, and offline scopes.
3. Requests to Google Drive using this user's access token work. Requests to Google Drive using my app's service account on this user's behalf also work. No requests return a 401.

I have tracked this behavior down to the same exception that aerodc was seeing:
`com.google.api.client.auth.oauth2.TokenResponseException: 401 Unauthorized`

I don't know why Google's servers are giving back a 401. I know that my client ID and secret are correct, because I am able to make some calls (as in the second scenario) without getting a 401. I don't think the problem has anything to do with refreshToken requests either; I am not explicitly requesting refresh tokens outside of whatever the Java client does automatically, and my code's behavior between the two scenarios doesn't change. Am I doing something wrong with scopes, then?

I know it's not the Java client's fault, per se - I'm quite happy that the exception is no longer just a NullPointerException. But I wish the Google servers would actually send an explanatory response body to begin with. That would help me understand what I'm doing wrong, as well as solving the NullPointerException problem indirectly. I feel like the fix to the NullPointerException is only half a fix; we simply have exchanged one exception type for another.

**Comment by mattwhisenhunt** [comment] 2017-10-11 22:16
This issue may no longer be relevant due to its age. Feel free to re-open.

**Closed by mattwhisenhunt** 2017-10-11 22:16 UTC
