### ISSUE TITLE
GoogleIdTokenVerifier usages unable to test.

### ISSUE THREAD

**Issue by dlazerka** [google/google-api-java-client#991] opened 2015-12-05 02:09 UTC
Hello, due to final methods classes we're unable to test code that uses GoogleIdTokenVerifier.

How simple test could look like

``` java
public class UnitTest {
    @Test
    public void testVerify() throws Exception {
        Unit unit = new Unit();
        unit.tokenVerifier = Mockito.mock(GoogleIdTokenVerifier.class);

        when(unit.tokenVerifier.verify(any(String.class)))
                .thenReturn(null);

        unit.verify(token); // throws NPE, because getJsonFactory() is null.
    }
}
```

but for some reason, GoogleIdTokenVerifier.getJsonFactory() is made final. Is there any reason for that? 

If the intent was to prevent anyone extending it from changing it behavior, then they can just extend IdTokenVerifier and do the same. Actually, that's our workaround currently -- we use IdTokenVerifier everywhere, and bind it to GoogleIdTokenVerifier in injection configuration.

Or use reflection. Or bytecode manipulation. That's how advanced testing frameworks like PowerMocks do, but we'd like to stay away from them (considered last resort for a library against you).

What is your recommended way to test it?

``` java
import com.google.api.client.googleapis.auth.oauth2.GoogleIdToken;
import com.google.api.client.googleapis.auth.oauth2.GoogleIdTokenVerifier;
import javax.inject.Inject;

public class Unit extends AbstractUnit {
    @Inject
    GoogleIdTokenVerifier tokenVerifier; // workaround using IdTokenVerifier here

    @Override
    protected void verify(String token) {
        GoogleIdToken idToken = GoogleIdToken.parse(tokenVerifier.getJsonFactory(), token);

        if (!tokenVerifier.verify(idToken)) {
            // Example. Note invalid idToken is needed.
            throw new InvalidKeyException("Invalid token for allegedly " + idToken.getPayload().getEmail());
        }
    }
}
```

**Comment by dlazerka** [comment] 2015-12-05 05:01
Actually, we found a way to test if the Unit code is like
```java
		GoogleIdToken idToken = tokenVerifier.verify(authToken);
		if (idToken == null) {
			GoogleIdToken invalidIdToken = GoogleIdToken.parse(jsonFactory, authToken);
			String email = invalidIdToken.getPayload().getEmail();
			throw new InvalidKeyException("Invalid token for allegedly " + email);
		}
```
looks not ideal, but at least works.

**Comment by dlazerka** [comment] 2015-12-05 08:50
Note I edited the issue significantly, please don't rely on GitHub notifications.

Tried to do
```java
GoogleIdToken invalidIdToken = jsonFactory.fromString(token, GoogleIdToken.class);
String email = invalidIdToken.getPayload().getEmail();
throw new InvalidKeyException("Invalid token for allegedly " + email);
```
and mock fromString(), but nope, it's final as well. And JsonParser.parse() too. Looks like the whole library is test-hostile.

Had to set up bloated and slow PowerMock: _PowerMock is a Java framework that allows you to unit test code normally regarded as untestable._
Any ideas? Is Google API Java Client really regarded as untestable?

**Comment by crbraun** [comment] 2017-06-09 22:43
Running into this myself with trying to mock out GoogleIdToken.Payload.  Ugh.

**Comment by dlazerka** [comment] 2017-06-09 23:47
@crbraun We ended up removing google-api-java-client from our codebase at all, sadly. Although in couple of places (e.g. GoogleAuthorizationCodeFlow) our hand-written code structure became way more readable.

**Comment by mattwhisenhunt** [comment] 2017-12-22 22:01
Duplicate of #973

**Closed by mattwhisenhunt** 2017-12-22 22:01 UTC
