### ISSUE TITLE
Cannot setup timeouts for Books API

### ISSUE THREAD

**Issue by dernasherbrezon** [google/google-api-java-client#965] opened 2015-08-21 12:51 UTC
Currently I'm using `BooksRequestInitializer`, but it doesn't have method `public void initialize(HttpRequest httpRequest) throws IOException` to setup timeouts.

This method was mentioned at https://developers.google.com/api-client-library/java/google-api-java-client/errors

**Comment by mattwhisenhunt** [comment] 2017-12-22 21:47
Duplicate of #964

**Closed by mattwhisenhunt** 2017-12-22 21:47 UTC
